# yaml-language-server: $schema=https://raw.githubusercontent.com/markrad/CertServer/master/config.schema.json

# All the values below have been set to their default value. If a secret key is provided, you should take steps to ensure this file is not world readable.

certServer:
  root: ./data                  # Root directory to keep database, certificates, and keys
  port: 4141                    # Webserver port number
  certificate: ''               # If both this and the key are provided the server will start in https
  key: ''                       # See above
  encryptKeys: false            # Encrypt keys in the file system
  useAuthentication: false      # Require authentication to access the server
  allowBasicAuth: false         # Allow basic authentication - should only be used for testing purposes
  subject:                      # Certificate subject defaults
    C: US
    ST: Washington
    L: Redmond
    O: None
    OU: None