version: "3.9"
services:
  certserver:
    container_name: certserver 
    restart: unless-stopped
    image: ghcr.io/markrad/certserver:1.2.17
    volumes:
      - /home/markrad/source/CertServer/docker/sampledirs/config:/config
      - /home/markrad/source/CertServer/docker/sampledirs/data:/data
    ports:
      - "4141:4141"
